services:

  postgres:
    image: pgvector/pgvector:pg17

    container_name: research-postgres

    environment:
      POSTGRES_DB: research_platform
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U postgres -d research_platform"
        ]
      interval: 5s
      timeout: 5s
      retries: 10


  backend:
    image: ranaabdullahtahir/research-intelligence-backend:latest

    container_name: research-backend

    env_file:
      - .env

    environment:
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432

    ports:
      - "8000:8000"

    volumes:
      - ./storage:/app/storage

    depends_on:
      postgres:
        condition: service_healthy


  frontend:
    image: ranaabdullahtahir/research-intelligence-frontend:latest

    container_name: research-intelligence-frontend

    ports:
      - "3000:80"

    depends_on:
      - backend


volumes:

  postgres_data: