"""create paper documents table

Revision ID: e105a31f39ef
Revises: 77b61daf9610
Create Date: 2026-08-20 14:39:38.123143

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e105a31f39ef'
down_revision: Union[str, Sequence[str], None] = '77b61daf9610'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('paper_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paper_id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('mime_type', sa.String(), nullable=False),
    sa.Column('storage_key', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('storage_key')
    )
    op.create_index(op.f('ix_paper_documents_id'), 'paper_documents', ['id'], unique=False)
    op.create_index(op.f('ix_paper_documents_paper_id'), 'paper_documents', ['paper_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_paper_documents_paper_id'), table_name='paper_documents')
    op.drop_index(op.f('ix_paper_documents_id'), table_name='paper_documents')
    op.drop_table('paper_documents')
    # ### end Alembic commands ###
